### ISSUE TITLE
Embed `updateinfo` into AppImage

### ISSUE THREAD

**Issue by KurtPfeifle** [ElTh0r0/iqpuzzle#12]
It's great to see this new AppImage being built and offered on the GitHub release page! :-)

Oh, and BTW: congratulations for getting your AppImage being listed as the 200th entry on [AppImageHub](appimage.github.io/apps/) 👍  🥇 

One tiny improvement for you to consider for future releases: this could be to embed the "updateinfo" string into the AppImage. This would allow users to easily and semi-automatically check for updates and upgrade their iQPuzzle if there is a new release available.

If you do not know how to achieve this, you could visit the [#AppImage channel on Freenode](https://webchat.freenode.net/?channels=appimage) and ask for help or for a patch so that .travis.yml will do that automatically for you.

---

<sup>(How these updates work from the p.o.v. of end users is described here: https://github.com/AppImage/AppImageUpdate/wiki/Example:-Step-by-step-walkthrough-with-%60appimageupdatetool%60 -- see also other articles in that wiki.)</sup>

**Comment by ElTh0r0** [comment]
Many thanks @KurtPfeifle! Enhancements are always welcome, especially since this is my first AppImage and I'm still learning about the possible features. I'll try to have a look on this soon :-)

**Comment by ElTh0r0** [comment]
In the end it was easy to implement, but took some time ;)
Starting with v1.2.3 iQPuzzle AppImage is built on OBS and including updateinfo automatically
https://download.opensuse.org/repositories/home:/ElThoro/AppImage/iQPuzzle-latest-x86_64.AppImage
