### ISSUE TITLE
Simultaneously quickly rotating and holding pieces removes exposed borders of other pieces

### ISSUE THREAD

**Issue by luihumberto** [ElTh0r0/iqpuzzle#19]
Steps to reproduce:

Q - any symmetrical piece, preferably a +

1. Load a board with multiple "holes" (barriers) and white border (such as most of the oddities, for better visibility)
2. Place a few pieces near the holes / border
3. Drag Q over one of the holes / near the board / over the board (try all three), but do not drop it.
4. Quickly rotate Q.
5. Most exposed borders of pieces on the board will disappear.

Additionally, if a piece D originally placed on the board is rotated such that it is partially out of the board, quick rotation dragging another piece nearby might cause the parts of piece D that are not on the board to visually disappear. 

Tested on iQPuzzle 1.1.1 on Puppy Linux (BionicPup64). 
Zooming in/out doesn't fix the issue. Easy to reproduce on oddity_003.

**Comment by luihumberto** [comment]
Also reproducible by rotating a piece into a overlapping state and repeatedly clicking on it.

**Comment by ElTh0r0** [comment]
Hi @luihumberto 
many thanks for reporting the issue!
Only to very, that I understood your explanation correctly. Is the below picture an example for your first example?
For this I might have a solution very soon, but need to test if I'm introducing other issues with it.
![grafik](https://user-images.githubusercontent.com/26674558/115588118-b34c0b00-a2ce-11eb-8650-4ae8ae07aa00.png)

> Additionally, if a piece D originally placed on the board is rotated such that it is partially out of the board, quick rotation dragging another piece nearby might cause the parts of piece D that are not on the board to visually disappear.

I'm sorry, I didn't get it. Can you please provide a screenshot?

**Comment by luihumberto** [comment]
![piece trimming bug](https://pipe.miroware.io/5edfb240dd072a448ca3480c/piece-trimming.png)
The blue outline shows the actual board rectangular area, which has a white background. The area that has a gray background is outside of that area. The piece highlighted in magenta was rotated to overlap with the hole, and was trimmed. (Don't mind the broken-looking ghost overlapping piece.)  
Notably, any pieces completely outside the board rectangle, not touching the blue outline, aren't affected at all. Also, when a piece is outside the rectangle, but touching the outline, only the borders that touch the outline are removed. A similar effect happens with the piece trimming:
![piece trimming bug: outline effect](https://pipe.miroware.io/5edfb240dd072a448ca3480c/trimming2.png)
In this case, the square highlighted in yellow was trimmed, but the two squares of the same piece that were outside the outline weren't. This one was on oddity_019.

**Comment by ElTh0r0** [comment]
Many thanks for the additional details! I think I could reproduce your examples and found a fix. If you are compiling the game yourself, you could already try and double check the latest commit 8915a5521c4abcfeb598b094ab65bcea38dfa7fe
I'll do some further tests and if everything is fine, I'll create a new release soon.

I see you are using v1.1.1, which is quite old. I'm not sure if BionicPup64 is 100% compatible with Ubuntu deb packages, but if so you could try to use the builds from my [Ubuntu PPA](https://launchpad.net/~elthoro/+archive/iqpuzzle) or you have to wait until somebody is going create packages it for BionicPuppy.

**Comment by ElTh0r0** [comment]
Fixed in v1.2.4
