### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by kiarn** [ElTh0r0/iqpuzzle#7]
Hello,

Not an issue, but I've done the french translation.
Unfortunately I can't do a pull request for it.
Here is the new ts file : https://github.com/kiarn/iqpuzzle/commit/13678d7cff4c8a22ae703fa44ff3fa6d3c790f68

Cheers.

**Comment by ElTh0r0** [comment]
Many thanks kiarn! I'll prepare a new release for the translation soon.

**Comment by ElTh0r0** [comment]
Hi @kiarn @mothsART 
Currently I'm preparing a new version, which includes a few new strings. I would appreciate very much, if you could translate them :)

**Comment by kiarn** [comment]
Hi @ElTh0r0,
I have updated the french ts file ( don't know how to generate the qm file ). Can you eventually add me to the contributor so I can push my changes ?
When not, I can try to do an pull request or to send you the file in an other way.

**Comment by mothsART** [comment]
kiarn : for generate files : 
1. modify the ts file
2. qmake iqpuzzle.pro
3. lrelease iqpuzzle.pro => compile .ts to .qm

Show your changes : 
3. make
4. launch ./iqpuzzle (with good locales)

**Comment by ElTh0r0** [comment]
Hi @kiarn,
everybody who creates a pull request is automatically added to the contributors, so you don't need any authorisation in advance. If possible, please create a fork of iqpuzzle, push the updated translation there and create pull request for the master branch ([GitHub help](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)).
I can create the .qm file with the updated .ts afterwards, if this is causing trouble for you.

**Comment by kiarn** [comment]
Hi @mothsART,
Thanks for your help, it's great. I've compile the qm file, but I get an error to compile iqpuzzle : 
`main.cpp:33:10: fatal error: QApplication: no such file or directory`

It's not relevant, I pushed my changes with a pull request, and I hope it's ok.

**Comment by kiarn** [comment]
Hi @ElTh0r0,

Thanks for your help, pull request is done.

**Comment by ElTh0r0** [comment]
Many thanks for your support @kiarn!
Regarding the build error: I could only image, that the Qt development libraries are not installed/cannot be found. iQPuzzle should be compatible with Qt 4 and 5. If you want to investigate the issue further: Which version are you using?

**Comment by kiarn** [comment]
I found it : I had to install qt4-dev-tools, and it works, thanks !

**Comment by mothsART** [comment]
:thumbsup:

**Comment by ElTh0r0** [comment]
Great!
Many thanks again for your commitment!
