### ISSUE TITLE
Wrong placement of the highscore window

### ISSUE THREAD

**Issue by OwlGale** [ElTh0r0/iqpuzzle#70]
Unlike the other windows (Preferences, About), which open in the middle of the game window, the Highscore window opens in a different location.

**Comment by ElTh0r0** [comment]
Good catch, thanks for reporting! Fix will be available in the next release

**Comment by OwlGale** [comment]
The same applies to the Hints window.

**Comment by ElTh0r0** [comment]
Thanks OwlGale! Now I really should have tackled all popup dialog windows positions :)
(there were some others in addition; mainly warning messages if something goes wrong)
